<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>biquad</name>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>8</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>in_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>in.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>out_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>out.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_3">
				<Value>
					<Obj>
						<type>1</type>
						<id>3</id>
						<name>a1</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>a1</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_4">
				<Value>
					<Obj>
						<type>1</type>
						<id>4</id>
						<name>a2</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>a2</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_5">
				<Value>
					<Obj>
						<type>1</type>
						<id>5</id>
						<name>b0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>b0</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_6">
				<Value>
					<Obj>
						<type>1</type>
						<id>6</id>
						<name>b1</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>b1</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_7">
				<Value>
					<Obj>
						<type>1</type>
						<id>7</id>
						<name>b2</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>b2</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_8">
				<Value>
					<Obj>
						<type>1</type>
						<id>8</id>
						<name>user_writing_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>28</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>22</id>
						<name>user_writing_V_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>63</item>
					<item>64</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>23</id>
						<name>b2_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>b2</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>66</item>
					<item>67</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>24</id>
						<name>b1_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>b1</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>68</item>
					<item>69</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>25</id>
						<name>b0_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>b0</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>70</item>
					<item>71</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>26</id>
						<name>a2_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>a2</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>72</item>
					<item>73</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>27</id>
						<name>a1_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>a1</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>74</item>
					<item>75</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>37</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>29</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>29</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>76</item>
					<item>77</item>
					<item>78</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>39</id>
						<name>tmp_4</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>37</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>37</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>tmp</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>80</item>
					<item>81</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>40</id>
						<name>tmp_6</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>82</item>
					<item>83</item>
				</oprand_edges>
				<opcode>fmul</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>41</id>
						<name>x1_load</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>84</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>42</id>
						<name>tmp_7</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>85</item>
					<item>86</item>
				</oprand_edges>
				<opcode>fmul</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>43</id>
						<name>tmp_8</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>87</item>
					<item>88</item>
				</oprand_edges>
				<opcode>fadd</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>44</id>
						<name>x2_load</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>89</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>45</id>
						<name>tmp_9</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>90</item>
					<item>91</item>
				</oprand_edges>
				<opcode>fmul</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>46</id>
						<name>tmp_s</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>92</item>
					<item>93</item>
				</oprand_edges>
				<opcode>fadd</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_24">
				<Value>
					<Obj>
						<type>0</type>
						<id>47</id>
						<name>y1_load</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>94</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_25">
				<Value>
					<Obj>
						<type>0</type>
						<id>48</id>
						<name>tmp_1</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>95</item>
					<item>96</item>
				</oprand_edges>
				<opcode>fmul</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_26">
				<Value>
					<Obj>
						<type>0</type>
						<id>49</id>
						<name>tmp_2</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>97</item>
					<item>98</item>
				</oprand_edges>
				<opcode>fsub</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_27">
				<Value>
					<Obj>
						<type>0</type>
						<id>50</id>
						<name>y2_load</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>99</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_28">
				<Value>
					<Obj>
						<type>0</type>
						<id>51</id>
						<name>tmp_3</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>100</item>
					<item>101</item>
				</oprand_edges>
				<opcode>fmul</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_29">
				<Value>
					<Obj>
						<type>0</type>
						<id>52</id>
						<name>output</name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>39</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>39</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>output</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>102</item>
					<item>103</item>
				</oprand_edges>
				<opcode>fsub</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_30">
				<Value>
					<Obj>
						<type>0</type>
						<id>53</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>41</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>41</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>104</item>
					<item>105</item>
					<item>303</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_31">
				<Value>
					<Obj>
						<type>0</type>
						<id>54</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>42</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>42</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>106</item>
					<item>107</item>
					<item>304</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_32">
				<Value>
					<Obj>
						<type>0</type>
						<id>55</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>43</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>43</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>108</item>
					<item>109</item>
					<item>305</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_33">
				<Value>
					<Obj>
						<type>0</type>
						<id>56</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>44</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>44</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>110</item>
					<item>111</item>
					<item>306</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_34">
				<Value>
					<Obj>
						<type>0</type>
						<id>57</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>46</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>46</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>113</item>
					<item>114</item>
					<item>115</item>
				</oprand_edges>
				<opcode>write</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_35">
				<Value>
					<Obj>
						<type>0</type>
						<id>58</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>47</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>116</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_36">
				<Value>
					<Obj>
						<type>0</type>
						<id>60</id>
						<name></name>
						<fileName>biquad.cpp</fileName>
						<fileDirectory>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</fileDirectory>
						<lineNumber>47</lineNumber>
						<contextFuncName>biquad</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/hildeb47/proj/ECE1373_GhostSynth/mods/biquad</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>biquad.cpp</first>
											<second>biquad</second>
										</first>
										<second>47</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>0</count>
			<item_version>0</item_version>
		</consts>
		<blocks class_id="16" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="17" tracking_level="1" version="0" object_id="_37">
				<Obj>
					<type>3</type>
					<id>38</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>7</count>
					<item_version>0</item_version>
					<item>22</item>
					<item>23</item>
					<item>24</item>
					<item>25</item>
					<item>26</item>
					<item>27</item>
					<item>37</item>
				</node_objs>
			</item>
			<item class_id_reference="17" object_id="_38">
				<Obj>
					<type>3</type>
					<id>59</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>20</count>
					<item_version>0</item_version>
					<item>39</item>
					<item>40</item>
					<item>41</item>
					<item>42</item>
					<item>43</item>
					<item>44</item>
					<item>45</item>
					<item>46</item>
					<item>47</item>
					<item>48</item>
					<item>49</item>
					<item>50</item>
					<item>51</item>
					<item>52</item>
					<item>53</item>
					<item>54</item>
					<item>55</item>
					<item>56</item>
					<item>57</item>
					<item>58</item>
				</node_objs>
			</item>
			<item class_id_reference="17" object_id="_39">
				<Obj>
					<type>3</type>
					<id>61</id>
					<name>._crit_edge</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>60</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="18" tracking_level="0" version="0">
			<count>50</count>
			<item_version>0</item_version>
			<item class_id="19" tracking_level="1" version="0" object_id="_40">
				<id>64</id>
				<edge_type>1</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>22</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_41">
				<id>67</id>
				<edge_type>1</edge_type>
				<source_obj>7</source_obj>
				<sink_obj>23</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_42">
				<id>69</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>24</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_43">
				<id>71</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>25</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_44">
				<id>73</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>26</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_45">
				<id>75</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>27</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_46">
				<id>76</id>
				<edge_type>1</edge_type>
				<source_obj>22</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_47">
				<id>77</id>
				<edge_type>2</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_48">
				<id>78</id>
				<edge_type>2</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_49">
				<id>81</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>39</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_50">
				<id>82</id>
				<edge_type>1</edge_type>
				<source_obj>39</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_51">
				<id>83</id>
				<edge_type>1</edge_type>
				<source_obj>25</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_52">
				<id>84</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>41</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_53">
				<id>85</id>
				<edge_type>1</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_54">
				<id>86</id>
				<edge_type>1</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_55">
				<id>87</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_56">
				<id>88</id>
				<edge_type>1</edge_type>
				<source_obj>42</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_57">
				<id>89</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>44</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_58">
				<id>90</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>45</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_59">
				<id>91</id>
				<edge_type>1</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>45</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_60">
				<id>92</id>
				<edge_type>1</edge_type>
				<source_obj>43</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_61">
				<id>93</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_62">
				<id>94</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_63">
				<id>95</id>
				<edge_type>1</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>48</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_64">
				<id>96</id>
				<edge_type>1</edge_type>
				<source_obj>27</source_obj>
				<sink_obj>48</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_65">
				<id>97</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_66">
				<id>98</id>
				<edge_type>1</edge_type>
				<source_obj>48</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_67">
				<id>99</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>50</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_68">
				<id>100</id>
				<edge_type>1</edge_type>
				<source_obj>50</source_obj>
				<sink_obj>51</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_69">
				<id>101</id>
				<edge_type>1</edge_type>
				<source_obj>26</source_obj>
				<sink_obj>51</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_70">
				<id>102</id>
				<edge_type>1</edge_type>
				<source_obj>49</source_obj>
				<sink_obj>52</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_71">
				<id>103</id>
				<edge_type>1</edge_type>
				<source_obj>51</source_obj>
				<sink_obj>52</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_72">
				<id>104</id>
				<edge_type>1</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>53</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_73">
				<id>105</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>53</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_74">
				<id>106</id>
				<edge_type>1</edge_type>
				<source_obj>52</source_obj>
				<sink_obj>54</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_75">
				<id>107</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>54</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_76">
				<id>108</id>
				<edge_type>1</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>55</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_77">
				<id>109</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>55</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_78">
				<id>110</id>
				<edge_type>1</edge_type>
				<source_obj>39</source_obj>
				<sink_obj>56</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_79">
				<id>111</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>56</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_80">
				<id>114</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>57</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_81">
				<id>115</id>
				<edge_type>1</edge_type>
				<source_obj>52</source_obj>
				<sink_obj>57</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_82">
				<id>116</id>
				<edge_type>2</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_83">
				<id>300</id>
				<edge_type>2</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>61</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_84">
				<id>301</id>
				<edge_type>2</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>59</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_85">
				<id>302</id>
				<edge_type>2</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>61</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_86">
				<id>303</id>
				<edge_type>4</edge_type>
				<source_obj>50</source_obj>
				<sink_obj>53</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_87">
				<id>304</id>
				<edge_type>4</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>54</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_88">
				<id>305</id>
				<edge_type>4</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>55</sink_obj>
			</item>
			<item class_id_reference="19" object_id="_89">
				<id>306</id>
				<edge_type>4</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>56</sink_obj>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="20" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="21" tracking_level="1" version="0" object_id="_90">
			<mId>1</mId>
			<mTag>biquad</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>3</count>
				<item_version>0</item_version>
				<item>38</item>
				<item>59</item>
				<item>61</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>25</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="25" tracking_level="0" version="0">
		<count>28</count>
		<item_version>0</item_version>
		<item class_id="26" tracking_level="0" version="0">
			<first>22</first>
			<second class_id="27" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>24</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>25</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>26</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>27</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>37</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>39</first>
			<second>
				<first>0</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>40</first>
			<second>
				<first>1</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>41</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>42</first>
			<second>
				<first>1</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>43</first>
			<second>
				<first>5</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>44</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>45</first>
			<second>
				<first>1</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>46</first>
			<second>
				<first>10</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>47</first>
			<second>
				<first>11</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>48</first>
			<second>
				<first>11</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>49</first>
			<second>
				<first>15</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>50</first>
			<second>
				<first>11</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>51</first>
			<second>
				<first>11</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>52</first>
			<second>
				<first>20</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>53</first>
			<second>
				<first>11</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>54</first>
			<second>
				<first>24</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>55</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>56</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>57</first>
			<second>
				<first>24</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>58</first>
			<second>
				<first>25</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>60</first>
			<second>
				<first>25</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="28" tracking_level="0" version="0">
		<count>3</count>
		<item_version>0</item_version>
		<item class_id="29" tracking_level="0" version="0">
			<first>38</first>
			<second class_id="30" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>59</first>
			<second>
				<first>0</first>
				<second>25</second>
			</second>
		</item>
		<item>
			<first>61</first>
			<second>
				<first>25</first>
				<second>25</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="31" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</regions>
	<dp_fu_nodes class_id="32" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="33" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

