// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbiquad.h"

extern XBiquad_Config XBiquad_ConfigTable[];

XBiquad_Config *XBiquad_LookupConfig(u16 DeviceId) {
	XBiquad_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBIQUAD_NUM_INSTANCES; Index++) {
		if (XBiquad_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBiquad_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBiquad_Initialize(XBiquad *InstancePtr, u16 DeviceId) {
	XBiquad_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBiquad_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBiquad_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

