// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbiquad.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBiquad_CfgInitialize(XBiquad *InstancePtr, XBiquad_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBiquad_Set_a1(XBiquad *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquad_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_A1_DATA, Data);
}

u32 XBiquad_Get_a1(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_A1_DATA);
    return Data;
}

void XBiquad_Set_a2(XBiquad *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquad_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_A2_DATA, Data);
}

u32 XBiquad_Get_a2(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_A2_DATA);
    return Data;
}

void XBiquad_Set_b0(XBiquad *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquad_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_B0_DATA, Data);
}

u32 XBiquad_Get_b0(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_B0_DATA);
    return Data;
}

void XBiquad_Set_b1(XBiquad *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquad_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_B1_DATA, Data);
}

u32 XBiquad_Get_b1(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_B1_DATA);
    return Data;
}

void XBiquad_Set_b2(XBiquad *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquad_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_B2_DATA, Data);
}

u32 XBiquad_Get_b2(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_B2_DATA);
    return Data;
}

void XBiquad_Set_user_writing_V(XBiquad *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquad_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_USER_WRITING_V_DATA, Data);
}

u32 XBiquad_Get_user_writing_V(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XBIQUAD_CTRL_BUS_ADDR_USER_WRITING_V_DATA);
    return Data;
}

