// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of a1
//        bit 31~0 - a1[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of a2
//        bit 31~0 - a2[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of b0
//        bit 31~0 - b0[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of b1
//        bit 31~0 - b1[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of b2
//        bit 31~0 - b2[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of user_writing_V
//        bit 0  - user_writing_V[0] (Read/Write)
//        others - reserved
// 0x3c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBIQUAD_CTRL_BUS_ADDR_A1_DATA             0x10
#define XBIQUAD_CTRL_BUS_BITS_A1_DATA             32
#define XBIQUAD_CTRL_BUS_ADDR_A2_DATA             0x18
#define XBIQUAD_CTRL_BUS_BITS_A2_DATA             32
#define XBIQUAD_CTRL_BUS_ADDR_B0_DATA             0x20
#define XBIQUAD_CTRL_BUS_BITS_B0_DATA             32
#define XBIQUAD_CTRL_BUS_ADDR_B1_DATA             0x28
#define XBIQUAD_CTRL_BUS_BITS_B1_DATA             32
#define XBIQUAD_CTRL_BUS_ADDR_B2_DATA             0x30
#define XBIQUAD_CTRL_BUS_BITS_B2_DATA             32
#define XBIQUAD_CTRL_BUS_ADDR_USER_WRITING_V_DATA 0x38
#define XBIQUAD_CTRL_BUS_BITS_USER_WRITING_V_DATA 1

